### ISSUE TITLE
Transient data MVP

### ISSUE THREAD

**Issue by That3Percent** [That3Percent/tree-buf#25]
Meta issue for collecting necessary features to support a release for transient data (eg: data over TCP without backward compatibility). This should be batteries included, but not necessarily support backward-compatible files.

- [ ] #19 - Add documentation
- [ ] #20 - Move options API to experimental
- [ ] #16 - Signed integer types
- [ ] #9 - Faster gorilla compression
- [ ] #21 - Semver policy
- [ ] #22 - Firestorm release
- [ ] #23 - Macro TODOs
